updated starting page by adding top trips fetching
IMurzinov/triptip_frontend pull request #61
Opened 2024-10-10 23:59 UTC by IMurzinov

2024-10-11 09:27 UTC, cosmofactory requested changes

2024-10-11 09:27 UTC, cosmofactory commented on src/pages/StartingPage/index.jsx
> +    const limitedData = data.slice(0, 5);
Что покажет, если данных нет?

2024-10-11 09:27 UTC, cosmofactory commented on src/pages/StartingPage/index.jsx
> +                    throw new Error("Network response was not ok");
В дальнейшем, проект станет больше и тебе придется обрабатывать больше ошибок, при этом большинство из них повторяюся, типа "Network response not ok" или "Failed to fetch data". Чтобы не хардкодить их в теле кода, а ссылаться на одно единственное место, лучше вынести их в отдельную переменную.
```

export const ERROR_MESSAGES = {
  NETWORK_ERROR: "Network response was not ok.",
  USER_FETCH_FAILED: "Failed to fetch user data.",
  TRIP_FETCH_FAILED: "Failed to fetch trips data.",
};
```
Таким образом, все наши ошибки будут консистентны, и ,если нам потребуется подредактировать сообщение об ошибке, то мы сделаем это в одном месте.

2024-10-11 09:27 UTC, cosmofactory commented on src/pages/StartingPage/index.jsx
> +        return <div>Одну секунду, загружаю...</div>;
То же самое с этой строчкой, медленная загрузка будет во многих местах, сейчас ты используешь эту фразу, потом будешь использовать другую, а потом вообще заменишь ее на какой нибудь компонент с символом загрузки. 
Вынеси state загрузки в отдельную переменную.

2024-10-11 09:27 UTC, cosmofactory commented on src/pages/StartingPage/index.jsx
> +        return <div>Error: {error.message}</div>;
Этот код покажет конечному пользователю ошибку, которая понятна только разработчику. Обычному пользователю она не нужна, он ничего не поймет, а злоумышленник на основании этой ошибки узнает больше о нашем внутреннем устройстве системы, архитекруте и некоторые данные из БД. 
Посмотри как тут сделано:
https://react.dev/reference/react/useTransition#displaying-an-error-to-users-with-error-boundary

2024-10-11 09:27 UTC, cosmofactory commented on src/pages/StartingPage/index.jsx
> +        const fetchTrips = async () => {
Файл index.jsx занимается тем, что отображает пользователю стартовую страницу. Пока здесь не много кода, но со временем его станет намног больше, если мы будем добавлять сюда все функции, которые требуются для его работы, то файл станет в 5000 строк, которые очень тяжело читать. 
При написании кода, есть принцим single responsibility, это когда компонент(функция, класс) делает только одну вещь и больше ничего. Раз index.jsx у нас занимается отображением информации, по пусть это и делает, соответственно нашу бизнес логику и блоки функций, которые подготавливают это, надо вынести в отдельный модуль.  

Это большое изменение, на него пока можешь забить, но со временем ты поймешь, что тебе надо подгрузить список поездок на нескольких страницах и, таким образом, тебе придется писать функцию fetchTrips для каждой из этих страниц, хотя суть ее не будет меняться. 
Как я понял, в реакте это делается при помощи хуков, есть стандартные, есть кастомные, посмотри.
https://react.dev/learn/reusing-logic-with-custom-hooks#extracting-your-own-custom-hook-from-a-component

2024-10-11 11:33 UTC, IMurzinov commented on src/pages/StartingPage/index.jsx
> +    const limitedData = data.slice(0, 5);
Ничего, будет пустой компонент просто. То бишь пустое место на странице

2024-10-11 11:33 UTC, IMurzinov commented on src/pages/StartingPage/index.jsx
> +    const limitedData = data.slice(0, 5);
Тоже надо на этот случай какую-то заглушку дефолтную ставить?

2024-10-11 11:38 UTC, cosmofactory commented on src/pages/StartingPage/index.jsx
> +    const limitedData = data.slice(0, 5);
Не знаю, надо посмотреть как это выглядит, поговори с Полиной, что в случае отсутствия поездок должно быть в этом месте

2024-10-13 00:59 UTC, cosmofactory approved these changes

2024-10-13 11:09 UTC, merged